### ISSUE TITLE
`npm bin` has been removed in Node 18 

### ISSUE THREAD

**Issue by MichaelGoberling** [adobe/asset-compute-integration-tests#39]
[npm bin has been removed with npm 9.0.0](https://github.blog/changelog/2022-10-24-npm-v9-0-0-released/#%E2%9A%A0%EF%B8%8F-notable-breaking-changes), which is what GitHub uses in actions for running Node 18. 

This means the [before each check for the Node executable path](https://github.com/adobe/asset-compute-integration-tests/blob/main/test/index.test.js#L55) will no longer work when this repo is updated to run tests using Node 18.

Solution could potentially be to use `npm list -g` and parse the output.

**Comment by shazron** [comment]
node `18.14.0` (released 2023-02-02) started to use npm `9.3.1` [[source](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#2023-02-02-version-18140-hydrogen-lts-bethgriggs-prepared-by-juanarbol)] latest node-18 is `18.14.2` (Mar 1, 2023)
